name: CI

on:
  push:
    branches:
      - master

env:
  UPLOAD_BUILD: true

jobs:
  xtensa-lx106:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: build
      id: script
      run: |
        chmod +x ./install.sh
        sudo ./install.sh
        echo "GCC=$PWD/crosstool-NG/build" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Generate tag
      id: tag
      if: env.UPLOAD_BUILD == 'true' && steps.script.outputs.status == 'success' && !cancelled()
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
        echo "::set-output name=status::success"

    - name: Upload tools
      uses: actions/upload-artifact@v2
      with:
        name: GCC
        path: ${{ env.GCC }}

